version: '3.9'
services:
 backend:
   image: qurom/building-estimator-ai:latest
   container_name: estimator-backend
   ports:
     - "8000:8000"
   env_file:
     - ./estimate-app/backend/.env  # ←必要に応じて調整
   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
   restart: always
 frontend:
   image: qurom/building-estimator-frontend:latest
   container_name: estimator-frontend
   ports:
     - "3000:80"
   stdin_open: true
   tty: true
   restart: always