name: CI/CD Pipeline
on:
 push:
   branches: [ main ]
   paths:
        - backend/estimate-app/**
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       platform: [linux/amd64, linux/arm64]
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Login to DockerHub
       uses: docker/login-action@v3
       with:
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build & Push Docker Image
       uses: docker/build-push-action@v6
       with:
         context: ./backend
         file: ./backend/Dockerfile # ← ここを修正
         platforms: ${{ matrix.platform }}
         push: true
         tags: qurom/building-estimator-ai:${{ github.sha }}
         cache-from: type=gha
         cache-to: type=gha,mode=max
     - name: Set IMAGE env
       run: echo "IMAGE=qurom/building-estimator-ai:${{ github.sha }}" >> $GITHUB_ENV
 deploy:
   needs: build-and-push
   runs-on: ubuntu-latest
   steps:
     - name: Dummy Deploy Step
       run: echo "Deploy phase (you can replace this with real logic)"
